bicycle_hire/blueprints/statistics/views.py
from flask import (Blueprint,
                   render_template,
                   flash,
                   url_for,
                   redirect,
                   request,
                   abort)
from flask_login import (current_user,
                         login_required
                        )
from bicycle_hire.blueprints.user.helpers.decorators import staff_login_required
from bicycle_hire.blueprints.statistics.forms import BookedBikesForm, WeekForm
from bicycle_hire.blueprints.bicycle.models import Booking, Location
from bicycle_hire.blueprints.payment.models import Payment
from bicycle_hire.blueprints.statistics.helpers.create_chart import create_booking_chart
from bicycle_hire.blueprints.statistics.helpers.create_chart import create_income_chart


stats = Blueprint('stats', __name__, template_folder='templates', url_prefix='/statistics')


@stats.route('weekly_income', methods=['GET', 'POST'])
@login_required
@staff_login_required()
def weekly_income():
    form = WeekForm()
    # Set the initial graph to none
    income_per_loc = None
    plot = None
    script = None
    div = None

    if form.validate_on_submit():
        if form.submit.data:

            # Get the initial income dictionary from database
            week = int(form.week.data)
            income_per_loc = Payment.get_weekly_income(week)

            # Convert the dictionary into two lists
            locations = list(income_per_loc.keys())
            income = list(income_per_loc.values())

            # Create the graph
            script, div = create_income_chart(locations, income)

    return render_template('statistics/weekly_income.html',
                            form = form,
                            script = script,
                            div = div
                          )


@stats.route('bicycles_booked', methods=['GET', 'POST'])
@login_required
@staff_login_required()
def bicycles_booked():
    form = BookedBikesForm()
    bicycle_per_loc = None
    plot = None
    script = None
    div = None

    if form.validate_on_submit():
        if form.submit.data:

            start_date = form.start_date.data
            end_date = form.end_date.data

            bicycle_per_loc = Booking.get_bike_stats(start_date, end_date)

            location = list(bicycle_per_loc.keys())
            values = list(bicycle_per_loc.values())

            script, div = create_booking_chart(location, values)

    return render_template('statistics/bicycles_booked.html',
                            form = form,
                            script = script,
                            div = div
                          )

bicycle_hire/blueprints/user/views.py
from flask import (Blueprint,
                   render_template,
                   flash,
                   url_for,
                   redirect,
                   request,
                   abort)
from flask_login import (login_user,
                         logout_user,
                         current_user,
                         login_required
                        )
from bicycle_hire.blueprints.user.forms import SignupForm, SigninForm
from bicycle_hire.blueprints.user.models import User
from bicycle_hire.blueprints.user.helpers.form_validation import flash_errors
from bicycle_hire.blueprints.user.helpers.url_redirect import is_safe_url

users = Blueprint('user', __name__, template_folder='templates', url_prefix='/account')

@users.route('/signup', methods=['GET', 'POST'])
def signup():
    # If user is already signed in
    if current_user.is_authenticated:
        flash("You are already signed in!", "info")
        return redirect(url_for('bicycles.index'))

    form = SignupForm()

    if form.validate_on_submit():
        new_user = User(form.email.data,
                        form.username.data,
                        form.password.data)
        new_user.db_commit()
        flash("Signed up successfully!", category="success")
        return redirect(url_for('user.signin'))
    else:
        flash_errors(form)
    
    return render_template('user/signup.html', form=form)

@users.route('/signin', methods=['GET', 'POST'])
def signin():
    # If user is already signed in
    if current_user.is_authenticated:
        flash("You are already signed in!", "info")
        return redirect(url_for('bicycles.index'))

    form = SigninForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user and login_user(user):
            flash("Signed in successfully!", category="success")

            # Get the next url that the user wants to access 
            next_page = request.args.get('next')
            form_id = request.args.get('form_id')
            # Handle the case when there's no next page
            if not next_page:
                return redirect(url_for('bicycles.index'))
            
            # Handle security concerns when following the next user url
            if not is_safe_url(next_page):
                return abort(400)
            
            return redirect(url_for(next_page, form_id=form_id))
    else:
        flash_errors(form)
    
    return render_template('user/signin.html', form=form)


@users.route('/signout')
@login_required
def signout():
    logout_user()
    flash('You have been signed out!', "success")
    return redirect(url_for('user.signin'))

bicycle_hire/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block map %} {% endblock %}
    <title>{% block title %} {% endblock %}</title>

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/bootstrap.min.css') }}">

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/font-awesome.min.css') }}">

    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous">
    </script>

</head>
<body>
    {% block header %} {% endblock %}
    {% block cover_image %} {% endblock %}
    <div class="container pt-2">
        {% block flash %} {% endblock %}

        {% block breadcrumb %} {% endblock %}

        {% block body %} {% endblock %}

    </div>

    {% block footer %} {% endblock %}
    <script
        src="{{ url_for('static', filename='scripts/vendor/bootstrap.min.js') }}">
    </script>
</body>
</html>

bicycle_hire/templates/site.html
{% extends "base.html" %}

{% block title %}Bicycle Hire{% endblock %}

{% block header %}
<!-- Bootstrap Example Navbar -->
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" style="font-size:16pt">
    <a class="navbar-brand" href="{{url_for('bicycles.index')}}" style="font-size:20pt">Bicycle Hire<sup>©</sup></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('bicycles.index')}}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('bicycles.booking')}}">Booking</a>
            </li>
            {% if current_user.is_authenticated and current_user.is_staff() %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Statistics
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{url_for('stats.weekly_income')}}">Weekly Income</a>
                        <a class="dropdown-item" href="{{url_for('stats.bicycles_booked')}}">Bicycles Booked</a>
                    </div>
                </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav mr-right">
            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('user.signout')}}">Sign out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('user.signin')}}">Sign in</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('user.signup')}}">Sign up</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% endblock %}

{% block flash %}
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
        {% for category, msg in messages %}
            <div class="alert alert-{{category}}">{{msg}}</div>
        {% endfor %}
        {% endif %}
    {% endwith %}
{% endblock %}

{% block cover_image %} {% endblock %}

{% block footer %}
    <!-- Footer -->
    <div class = "card-footer" style="margin-top:4%; margin-bottom: 0%; position: static"> 
        <div class = "container">
            <div class = "row">
                <div class = "col-sm">
                    <h4>If you have any enquiries, please do not hesitate to contact us</h4>
                    <ul class="email" style="list-style-image: url('/static/images/email.png')">
                        <li><a href = "mailto:bicycleHire@outlook.com">bicycleHire@outlook.com</a></li>
                    </ul>
                    <ul class="phone" style="list-style-image: url('/static/images/phone.png')">
                        <li><a href = "callto:01942123456">01942123456</a> (from 9am to 5pm)</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3 elegant-color-dark">
        Copyright © 2018 <a href="{{url_for('bicycles.index')}}">Bicycle Hire</a>
        <br>
        Powered by Group 14
    </div>
{% endblock %}